"""
Django settings for back project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ahv_lb73x9eypae8pqv9x0)58ced3azb5(6$h667*x2w2rp=is'

# SECURITY WARNING: don't run with debug turned on in production!
# Activé pour le développement local afin de servir les médias et faciliter le debug
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '42ccf785e2b0.ngrok-free.app', '.onrender.com', 'flashxship.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'corsheaders',
    'vente',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # Placer notre middleware avant CsrfViewMiddleware pour marquer les URLs exemptées
    'vente.middleware.CSRFExemptMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'vente.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Désactiver CSRF pour les vues d'API
CSRF_EXEMPT_URLS = [
    r'^/api/admin/orders/\d+/confirm/$',
    r'^/api/admin/orders/\d+/reject/$',
    r'^/api/admin/orders/\d+/ship/$',
    r'^/api/admin/orders/\d+/deliver/$',
    r'^/api/admin/messages/\d+/respond/$',
    r'^/create_payment_session/$',
    r'^/contact/$',
    r'^/stripe-webhook/$',
]


ROOT_URLCONF = 'back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'back.wsgi.application'

SPECTACULAR_SETTINGS = {
    'TITLE': 'FLASHXSHIP API',
    'DESCRIPTION': 'Une application web de vente en ligne',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql',
       'NAME': 'flashxship',
       'USER': 'flashxship_user',
       'PASSWORD': 'XtEYyAKgFVPiG1YcGWleKow5XCNPqdO1',
       'HOST': 'dpg-d2ednm2li9vc73du7ad0-a',
       'PORT': '5432',  # par défaut pour PostgreSQL
   }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Porto-Novo'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
# Les médias sont dans le dossier parent (back/media)
MEDIA_ROOT = BASE_DIR.parent / 'media'


# Stripe Configuration
STRIPE_SECRET_KEY = "sk_test_51QyFvJITZNLvxKirz8scuDKdsB7r4Jk0QKDZHLvSVuMLHA9eLvBDmUR5xaLHtdShWnONBgF7fNhghoBLQo3V4GsR00hCyt3iEw"
STRIPE_PUBLIC_KEY = "pk_test_51QyFvJITZNLvxKira0vz3UuTdu4fYW6qci1k9I1pnfOWOXwAkKWNZGGHPz8LuNkJmtLEzK811tBgbwZBCq3v1UIG0001WUesWt"
STRIPE_WEBHOOK_SECRET = "whsec_AGbGFaalEFYDaFtTfZOhEtK2jWHQtwdy"  # À configurer dans le dashboard Stripe

# Frontend URL
FRONTEND_URL = "http://localhost:3000"

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Par défaut Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'celibertaizonou22@gmail.com'
EMAIL_HOST_PASSWORD = 'qdhxfwekoqrfbkpa'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# En développement, conserver le backend SMTP par défaut (à moins de le surcharger via variables d'environnement)

# Authentication URLs
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://42ccf785e2b0.ngrok-free.app",
    "https://.onrender.com",
    "https://flashxship.vercel.app"
]

CORS_ALLOW_CREDENTIALS = True

# Permettre les cookies cross-origin
CORS_ALLOW_ALL_ORIGINS = False
CORS_EXPOSE_HEADERS = ['*']

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Session Configuration pour cross-origin
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # True en production avec HTTPS
SESSION_COOKIE_HTTPONLY = False  # Permettre l'accès JavaScript
SESSION_COOKIE_DOMAIN = None  # Permettre tous les domaines en développement
